apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    app.openshift.io/vcs-ref: master
    app.openshift.io/vcs-uri: https://github.com/jwennerberg/vote-api.git
  labels:
    app: api
    app.kubernetes.io/component: api
    app.kubernetes.io/instance: api
    app.kubernetes.io/name: golang
    app.kubernetes.io/part-of: vote
    app.openshift.io/runtime: golang
    app.openshift.io/runtime-version: 1.11.5
  name: api
spec:
  tags:
  - name: latest
    from:
      kind: DockerImage
      name: quay.io/openshift-pipeline/vote-api:latest
